### ISSUE TITLE
URL is not a constructor when running teletype-client js in a browser

### ISSUE THREAD

**Issue by sunix** [atom/teletype-client#43]
Hi there,
I'm facing an issue in `rest-gateway.js` when running it in a browser

```
const {URL} = require('url')
....
    const url = new URL(relativeURL, this.baseURL).toString()
```
is throwing an exception `URL is not a constructor`Uncaught TypeError: URL is not a constructor`

I'm currently trying to find a workaround to this one but haven't found any so far

**Comment by jasonrudolph** [comment]
> I'm facing an issue in `rest-gateway.js` when running it in a browser

:wave: Hi @sunix! Thanks for trying out teletype-client. :smile:

So far, we've only run teletype-client [via Node 7+](https://github.com/atom/teletype-client/tree/ede577e6048d6faf42007205e83013bb03da126d#dependencies). In the near term, we probably don't have the resources to provide support for people attempting to run teletype-client in the browser, so I'm going to close this issue for now. I hope that makes sense.

That said, I do :heart: the idea of teletype-client being usable within a browser. If you continue to pursue running teletype-client in the browser, I'll be cheering you on from the sidelines. 😅

**Comment by sunix** [comment]
yes sure, I'll try to have this working :)
