### ISSUE TITLE
Does not build on windows 10

### ISSUE THREAD

**Issue by markaduol** [atom/teletype-client#69]
See https://discuss.newrelic.com/t/newrelic-native-metrics-does-not-install-on-windows-10/47378 for further details

**Comment by markaduol** [comment]
See https://stackoverflow.com/questions/51526377/the-target-tnative-metrics-does-not-exist-in-the-project for possible solution

**Comment by Arcanemagus** [comment]
Closing this as none of the above links appear to have anything to do with `teletype-client`. If you feel this is incorrect please enlighten us as to how this is related 😉.
